# -*- mode: ruby -*-
# vi: set ft=ruby :

defaultbox = "ubuntu/trusty64"
box = ENV['BOX'] || defaultbox

ENV['ANSIBLE_ROLES_PATH'] = "../../"

Vagrant.configure(2) do |config|

  config.vm.box = box

  config.vm.define "prometheus" do |prometheus_cfg|
    prometheus_cfg.vm.hostname = "prometheus.vagrant"
    prometheus_cfg.vm.network "private_network", type: "dhcp"
    prometheus_cfg.vm.provider :virtualbox do |v|
      v.name = "prometheus"
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.sudo = true
    ansible.groups = {
      "vagrant" => ["prometheus"],
    }
    ansible.extra_vars = {
      ansible_ssh_user: 'vagrant',
      hbase_standalone:   true,
    }

  end

end
